version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vivek@123
      POSTGRES_DB: postgres

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_DATABASE: nest-core
